# To validate changes, use an online parser, eg.
# http://yaml-online-parser.appspot.com/

version: 2.1

var_1: &default_docker_image circleci/node:12.13-browsers
var_2: &cache_key mosaic-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}-9.1.0

var_3: &job_defaults
    working_directory: ~/mosaic
    docker:
        - image: *default_docker_image

# Restores the cache that could be available for the current Yarn lock file.
var_5: &restore_cache
    restore_cache:
        key: *cache_key

# After checkout, rebase on top of master.
# Similar to travis behavior, but not quite the same.
# See https://discuss.circleci.com/t/1662
var_4: &checkout_code
    checkout:
        # After checkout, rebase on top of master. By default, PRs are not rebased on top of master,
        # which we want. See https://discuss.circleci.com/t/1662
        post: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

orbs:
    sonarcloud: sonarsource/sonarcloud@1.0.0
    snyk: snyk/snyk@0.0.8

jobs:

    install:
        <<: *job_defaults
        steps:
            - checkout
            - *restore_cache
            - run: yarn install --frozen-lockfile --non-interactive
            - save_cache:
                  key: *cache_key
                  paths:
                      - ~/.cache/yarn
                      - node_modules
            - persist_to_workspace:
                  root: ~/mosaic
                  paths:
                      - .

    dependencies_audit:
        <<: *job_defaults
        steps:
            - attach_workspace:
                  at: ~/mosaic
            - snyk/scan:
                  fail-on-issues: false

    validate_licenses:
        <<: *job_defaults
        steps:
            - attach_workspace:
                  at: ~/mosaic
            - run: yarn run valid:lic

    linters:
        <<: *job_defaults
        steps:
            - attach_workspace:
                  at: ~/mosaic
            - run: yarn run linter:mosaic:json
            - run: yarn run linter:styles:json
            - persist_to_workspace:
                  root: .
                  paths:
                      - ./dist/reports

    build_packages:
        <<: *job_defaults
        steps:
            - attach_workspace:
                  at: ~/mosaic
            - run: yarn run build:cdk
            - run: yarn run build:mosaic-moment-adapter
            - run: yarn run build:mosaic
            - run: yarn run styles:built-all
            - persist_to_workspace:
                  root: ~/mosaic
                  paths:
                      - .

    build_mosaic_docs:
        <<: *job_defaults
        steps:
            - attach_workspace:
                  at: ~/mosaic
            - run:
                  name: Setup Environment Variables
                  command: |
                      echo 'export CI_PREVIEW=true' >> $BASH_ENV
                      echo 'export SHORT_GIT_HASH=$(git rev-parse --short=7 $CIRCLE_SHA1)' >> $BASH_ENV
                      echo 'export CIRCLE_PULL_REQUEST_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | cut -d"/" -f7)' >> $BASH_ENV
                      source $BASH_ENV
            - run: printenv
            - run: yarn run build:mosaic-examples-module
            - run: yarn run build:mosaic-examples
            - run: yarn run build:docs
            - run: yarn run docs:prod-build --progress false --base-href /mosaic-previews/pr$CIRCLE_PULL_REQUEST_NUMBER-$SHORT_GIT_HASH/ --output-path dist/releases/mosaic-docs/pr$CIRCLE_PULL_REQUEST_NUMBER-$SHORT_GIT_HASH/
            - persist_to_workspace:
                  root: ~/mosaic
                  paths:
                      - .

    test_unit_cdk:
        <<: *job_defaults
        steps:
            - attach_workspace:
                  at: ~/mosaic
            - run:
                  command: yarn run unit:cdk
                  environment:
                      JUNIT_REPORT_PATH: junit/
                      JUNIT_REPORT_NAME: test-results.xml
                  when: always
            - store_test_results:
                  path: junit
            - store_artifacts:
                  path: junit
            - persist_to_workspace:
                  root: .
                  paths:
                      - ./dist/coverage

    test_unit_mosaic:
        <<: *job_defaults
        steps:
            - attach_workspace:
                  at: ~/mosaic
            - run:
                  command: yarn run unit:mosaic
                  environment:
                      JUNIT_REPORT_PATH: junit/
                      JUNIT_REPORT_NAME: test-results.xml
                  when: always
            - store_test_results:
                  path: junit
            - store_artifacts:
                  path: junit
            - persist_to_workspace:
                  root: .
                  paths:
                      - ./dist/coverage

    test_unit_mosaic-moment-adapter:
        <<: *job_defaults
        steps:
            - attach_workspace:
                  at: ~/mosaic
            - run:
                  command: yarn run unit:mosaic-moment-adapter
                  environment:
                      JUNIT_REPORT_PATH: junit/
                      JUNIT_REPORT_NAME: test-results.xml
                  when: always
            - store_test_results:
                  path: junit
            - store_artifacts:
                  path: junit
            - persist_to_workspace:
                  root: .
                  paths:
                      - ./dist/coverage

    sonar:
        <<: *job_defaults
        steps:
            - attach_workspace:
                  at: ~/mosaic
            - sonarcloud/scan

    snapshot_publish:
        <<: *job_defaults
        steps:
            - *checkout_code
            - *restore_cache
            - attach_workspace:
                  at: ~/mosaic
            - add_ssh_keys:
                  fingerprints:
                      - "c3:de:eb:9c:82:70:a8:23:f3:4e:92:b8:07:d2:22:df"
            - run: ./scripts/deploy/publish-artifacts.sh

    preview_mosaic_docs:
        <<: *job_defaults
        steps:
            - add_ssh_keys:
                  fingerprints:
                      - "c3:de:eb:9c:82:70:a8:23:f3:4e:92:b8:07:d2:22:df"
            - *checkout_code
            - *restore_cache
            - attach_workspace:
                  at: ~/mosaic
            - run: printenv
            - run:
                  name: Setup Environment Variables
                  command: |
                      echo 'export CI_PREVIEW=true' >> $BASH_ENV
                      echo 'export SHORT_GIT_HASH=$(git rev-parse --short=7 $CIRCLE_SHA1)' >> $BASH_ENV
                      echo 'export CIRCLE_PULL_REQUEST_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | cut -d"/" -f7)' >> $BASH_ENV
                      source $BASH_ENV
            - run: printenv
            - run: yarn run docs:publish-preview

    cleanup_preview_mosaic_docs:
        <<: *job_defaults
        steps:
            - add_ssh_keys:
                  fingerprints:
                      - "c3:de:eb:9c:82:70:a8:23:f3:4e:92:b8:07:d2:22:df"
            - *checkout_code
            - *restore_cache
            - run: yarn run docs:cleanup-preview

workflows:
    version: 2
    default_workflow:
        jobs:
            # 1 Group
            - install

            # 2 Group
            - dependencies_audit:
                  requires:
                      - install
            - validate_licenses:
                  requires:
                      - install
            - linters:
                  requires:
                      - install

            # 3 Group
            - build_packages:
                  requires:
                      - validate_licenses
                      - linters
                      - dependencies_audit

            # 6 Group
            - test_unit_cdk:
                  requires:
                      - build_packages

            - test_unit_mosaic-moment-adapter:
                  requires:
                      - build_packages

            - test_unit_mosaic:
                  requires:
                      - build_packages

            - build_mosaic_docs:
                  requires:
                      - test_unit_mosaic
                      - test_unit_cdk
                      - test_unit_mosaic-moment-adapter

            # 7 Group

            - sonar:
                  context: SonarCloud
                  requires:
                      - test_unit_cdk
                      - test_unit_mosaic-moment-adapter
                      - test_unit_mosaic

            - snapshot_publish:
                  requires:
                      - test_unit_cdk
                      - test_unit_mosaic-moment-adapter
                      - test_unit_mosaic
                  filters:
                      branches:
                          only:
                              - master

            - preview_mosaic_docs:
                  requires:
                      - build_mosaic_docs

            - cleanup_preview_mosaic_docs:
                  requires:
                      - install
                  filters:
                      branches:
                          only: master
